# Generated by Django 6.0.4 on 2026-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_district_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
