# Generated by Django 6.0.4 on 2026-05-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_remove_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, default='New', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='Standard Pack', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('sold_out', 'Sold Out'), ('up_coming', 'Up_coming')], default='in_stock', max_length=20),
        ),
    ]
